/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfiches;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jeutrinome.Controle;
import jeutrinome.Joueur;
import jeutrinome.Pion;
import jeutrinome.Plateau;

/**
 *
 * @author tobia
 */
public class FAccueil extends javax.swing.JFrame {

    private FPlateau fichPlateau; //instance de la classe FPlateau, fiche de jeu du trinôme

    /**
     * Creates new form FAccueil
     */
    public FAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNouvellePartie = new javax.swing.JButton();
        bReprendre = new javax.swing.JButton();
        bQuitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lPseudoJ1 = new javax.swing.JLabel();
        lPseudoJ2 = new javax.swing.JLabel();
        tfJ1 = new javax.swing.JTextField();
        tfJ2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");

        bNouvellePartie.setBackground(new java.awt.Color(0, 204, 0));
        bNouvellePartie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bNouvellePartie.setForeground(new java.awt.Color(255, 255, 255));
        bNouvellePartie.setText("Nouvelle Partie");
        bNouvellePartie.setToolTipText("");
        bNouvellePartie.setBorderPainted(false);
        bNouvellePartie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNouvellePartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNouvellePartieActionPerformed(evt);
            }
        });

        bReprendre.setBackground(new java.awt.Color(0, 204, 0));
        bReprendre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bReprendre.setForeground(new java.awt.Color(255, 255, 255));
        bReprendre.setText("Reprendre");
        bReprendre.setBorderPainted(false);
        bReprendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReprendreActionPerformed(evt);
            }
        });

        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jeu du Trinôme");
        jLabel1.setOpaque(true);

        lPseudoJ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lPseudoJ1.setText("Pseudo Joueur 1");

        lPseudoJ2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lPseudoJ2.setText("Pseudo Joueur 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bReprendre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNouvellePartie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lPseudoJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfJ1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPseudoJ2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPseudoJ2)
                    .addComponent(lPseudoJ1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(bNouvellePartie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bReprendre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(bQuitter))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);//quitte la fiche
    }//GEN-LAST:event_bQuitterActionPerformed

    private void bNouvellePartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNouvellePartieActionPerformed
        //Initialisation les différentes variables pour créer un plateau et 2 Joueurs. Grâce à cela, nous pouvons créer un contrôle et donc créer une nouvelle partie
        String ZoneRougeJ2[];
        ZoneRougeJ2 = new String[3];//Tableau de String de taille 3
        ZoneRougeJ2[0] = "EK";
        ZoneRougeJ2[1] = "FK";
        ZoneRougeJ2[2] = "GK";
        String ZoneRougeJ1[];
        ZoneRougeJ1 = new String[3];
        ZoneRougeJ1[0] = "EA";
        ZoneRougeJ1[1] = "FA";
        ZoneRougeJ1[2] = "GA";
        String Case[];
        String Case2;
        Case = new String[121];
        int cpt = 0;
        for (int i = 65; i < 76; i++) {
            for (int j = 65; j < 76; j++) {
                char a = (char) i;
                String c = Character.toString(a);
                char b = (char) j;
                String d = Character.toString(b);
                Case2 = (c + d);
                Case[cpt] = Case2;
                cpt++;
            }
        }
        Plateau T1 = new Plateau(23, 23, ZoneRougeJ1, ZoneRougeJ2, Case);
        String Pseudo1 = tfJ1.getText();//On récupère le pseudo du Joueur depuis le JTextField
        String Pseudo2 = tfJ2.getText();//On récupère le pseudo du Joueur depuis le JTextField
        String couleur1 = "rouge";
        String couleur2 = "verte";
        Pion PionJ1[] = new Pion[15];
        Pion PionJ2[] = new Pion[15];
        Joueur J1 = new Joueur(Pseudo1, couleur1, PionJ1);//création du Joueur J1
        Joueur J2 = new Joueur(Pseudo2, couleur2, PionJ2);//création du Joueur J2
        Controle C1 = new Controle(J1, J2, T1);//création du contrôle
        try {
            C1.NouvellePartie();
        } catch (IOException ex) {
            Logger.getLogger(FAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        fichPlateau = new FPlateau(this, false, C1, J1, J2, false);//création d’une fenêtre non modale
        this.setVisible(false);//Rend la fiche Accueil invisible
        fichPlateau.setVisible(true);//la fiche Plateau devient visible
    }//GEN-LAST:event_bNouvellePartieActionPerformed

    private void bReprendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReprendreActionPerformed
        //Permet de reprendre la partie Sauvegarder. On réinitialise toutes les variables pour pouvoir faire appel à la méthode Chargement.
        String ZoneRougeJ2[];
        ZoneRougeJ2 = new String[3];
        ZoneRougeJ2[0] = "EK";
        ZoneRougeJ2[1] = "FK";
        ZoneRougeJ2[2] = "GK";
        String ZoneRougeJ1[];
        ZoneRougeJ1 = new String[3];
        ZoneRougeJ1[0] = "EA";
        ZoneRougeJ1[1] = "FA";
        ZoneRougeJ1[2] = "GA";
        String Case[];
        String Case2;
        Case = new String[121];
        int cpt = 0;
        for (int i = 65; i < 76; i++) {
            for (int j = 65; j < 76; j++) {
                char a = (char) i;
                String c = Character.toString(a);
                char b = (char) j;
                String d = Character.toString(b);
                Case2 = (c + d);
                Case[cpt] = Case2;
                cpt++;
            }
        }
        Plateau T1 = new Plateau(23, 23, ZoneRougeJ1, ZoneRougeJ2, Case);
        String Pseudo1 = tfJ1.getText();
        String Pseudo2 = tfJ2.getText();
        String couleur1 = "rouge";
        String couleur2 = "vert";
        Pion PionJ1[] = new Pion[15];
        Pion PionJ2[] = new Pion[15];
        Joueur J1 = new Joueur(Pseudo1, couleur1, PionJ1);
        Joueur J2 = new Joueur(Pseudo2, couleur2, PionJ2);
        Controle C1 = new Controle(J1, J2, T1);
        try {
            C1 = C1.Chargement();
            fichPlateau = new FPlateau(this, false, C1, J1, J2, true);//création d’une fenêtre non modale
            this.setVisible(false);//Rend la fiche Accueil invisible
            fichPlateau.setVisible(true);//la fiche Plateau devient visible
        } catch (IOException ex) {
            Logger.getLogger(FAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bReprendreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNouvellePartie;
    private javax.swing.JButton bQuitter;
    private javax.swing.JButton bReprendre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lPseudoJ1;
    private javax.swing.JLabel lPseudoJ2;
    private javax.swing.JTextField tfJ1;
    private javax.swing.JTextField tfJ2;
    // End of variables declaration//GEN-END:variables
}
